name: Format Sources

on: [ push, pull_request ]

jobs:

  check-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace --fix-imports-only"
          skip-commit: true
      - name: Print diffs
        run: git --no-pager diff --exit-code